### ISSUE TITLE
No detected text with line break

### ISSUE THREAD

**Issue by hortigado** [bikram0000/getx_translator#4]
![image](https://github.com/bikram0000/getx_translator/assets/42924254/557fbb24-fc6a-411f-992f-aa4acb8cd36e)
Hi it text with line break no is detected

**Comment by bikram0000** [comment]
Please use latest version from git url to solve this issue, I will soon update it on pub.dev

**Comment by hortigado** [comment]
Hello again, I have done some recent tests and again this problem occurs: when the .tr is moved to a new line by the code formatter, the command does not detect it.
