### ISSUE TITLE
need function onpressed if pressed then language should be change from en to hi

### ISSUE THREAD

**Issue by mehdinathani** [bikram0000/getx_translator#5]
need function onpressed if pressed then language should be change from en to hi

i have json files auto generated from getx_translator google sheet

**Comment by bikram0000** [comment]
Hello @mehdinathani 
This package is only help to generate the json translated file. If you want to use those json files, you can follow the official guidelines from getx or you can check the below link to step by step guide to use those json file to change language.

https://medium.com/@magnigeeks3/localization-in-flutter-with-getx-translator-eadd99946a5e
